// supabase/seed.mjs — Seed all data into Supabase
// Run: node supabase/seed.mjs
import { createClient } from '@supabase/supabase-js';
import 'dotenv/config';

const url = process.env.VITE_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) { console.error('Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY'); process.exit(1); }

const sb = createClient(url, key);

async function upsert(table, rows) {
  const { error } = await sb.from(table).upsert(rows, { onConflict: 'id' });
  if (error) { console.error(`✗ ${table}:`, error.message); return false; }
  console.log(`✓ ${table}: ${rows.length} rows`);
  return true;
}

// ── Categories ──
const categories = [
  { id:"mahayagya", title:"Mahayagya & Katha", slug:"mahayagya-katha", description:"Grand multi-day spiritual events — Bhagwat Katha, Ram Katha, Sundarkand, and massive yagyas for deep karmic purification.", icon:"fire", image:"/assets/categories/mahayagya.jpg", featured:true, sort_order:1 },
  { id:"samskara", title:"Vedic Samskaras", slug:"vedic-samskaras", description:"Sacred life-milestone ceremonies — Vivah, Namkaran, Mundan, Upanayana, Annaprashan — performed with full Vedic precision.", icon:"flower", image:"/assets/categories/samskara.jpg", featured:true, sort_order:2 },
  { id:"regular", title:"Regular Pujas", slug:"regular-pujas", description:"Household pujas for everyday occasions — Satyanarayan, Griha Pravesh, Rudrabhishek, Ganesh Puja, and more.", icon:"pray", image:"/assets/categories/regular.jpg", featured:true, sort_order:3 },
  { id:"astrological", title:"Navagraha & Dosh Nivaran", slug:"navagraha-dosh-nivaran", description:"Planetary appeasement and dosh removal — Mangal Dosh, Kaal Sarp Dosh, Shani Shanti, Rahu-Ketu, and all 9 planets.", icon:"star", image:"/assets/categories/astrological.jpg", featured:true, sort_order:4 },
  { id:"prosperity", title:"Lakshmi & Prosperity", slug:"lakshmi-prosperity", description:"Wealth and abundance rituals — Lakshmi Puja, Kuber Puja, Sri Sukta Havan, and business-growth pujas.", icon:"lotus", image:"/assets/categories/prosperity.jpg", featured:true, sort_order:5 },
  { id:"health", title:"Health & Protection", slug:"health-protection", description:"Pujas for healing, longevity, and divine protection — Maha Mrityunjaya, Dhanvantari, Sudarshan Havan, and Kavach pujas.", icon:"shield", image:"/assets/categories/health.jpg", featured:false, sort_order:6 },
  { id:"shanti", title:"Shanti & Peace", slug:"shanti-peace", description:"Pujas to restore harmony — Nakshatra Shanti, Bhoomi Puja, Graha Shanti, and Sarva Karya Siddhi rituals.", icon:"peace", image:"/assets/categories/shanti.jpg", featured:false, sort_order:7 },
  { id:"festival", title:"Festival Pujas", slug:"festival-pujas", description:"Celebrate festivals with authentic rituals — Navratri, Ganesh Chaturthi, Shivratri, Janmashtami, and more.", icon:"calendar", image:"/assets/categories/festival.jpg", featured:true, sort_order:8 },
  { id:"pitru", title:"Ancestral & Pitru Karma", slug:"ancestral-pitru", description:"Sacred rites for ancestors — Pind Daan, Shraddh, Narayan Bali, Tarpan, and Asthi Visarjan for ancestral peace.", icon:"ancestry", image:"/assets/categories/pitru.jpg", featured:false, sort_order:9 },
  { id:"tantra", title:"Tantra & Shakti Pujas", slug:"tantra-shakti", description:"Powerful Tantrik pujas — Baglamukhi, Kali, Bhairav, and Das Mahavidya pujas for protection and victory.", icon:"trident", image:"/assets/categories/tantra.jpg", featured:false, sort_order:10 },
];

// ── Pandits ──
const pandits = [
  { id:"p1", name:"Acharya Veda Prakash Shastri", slug:"acharya-veda-prakash", title:"Vedic Scholar & Katha Vyas", experience:25, experience_label:"25+ Years", expertise:["Bhagwat Katha","Ram Katha","Sundarkand","Rudrabhishek","Mahayagya"], specializations:["mahayagya","regular"], languages:["Hindi","Sanskrit","English"], rating:4.9, reviews:320, completed_pujas:2800, location:"Varanasi, UP", available:true, featured:true, image_url:"/assets/pandits/p1.jpg", bio:"A renowned scholar of the Vedas with immense expertise in conducting grand yagyas and reciting Srimad Bhagwat.", certifications:["Shastri (Sampurnanand Sanskrit University)","Acharya in Vedic Studies"] },
  { id:"p2", name:"Shastri Rajendra Tiwari", slug:"shastri-rajendra-tiwari", title:"Karmakand Specialist", experience:15, experience_label:"15+ Years", expertise:["Griha Pravesh","Satyanarayan Katha","Vivah","Namkaran","Lakshmi Puja"], specializations:["regular","samskara","prosperity"], languages:["Hindi","Sanskrit","Bhojpuri"], rating:4.8, reviews:180, completed_pujas:1500, location:"Prayagraj, UP", available:true, featured:true, image_url:"/assets/pandits/p2.jpg", bio:"Specializes in household pujas, samskaras, and prosperity rituals.", certifications:["Shastri (Allahabad University)","Karmakand Visharad"] },
  { id:"p3", name:"Pandit Ramakant Sharma", slug:"pandit-ramakant-sharma", title:"Jyotish & Vastu Expert", experience:20, experience_label:"20+ Years", expertise:["Navagraha Shanti","Kaal Sarp Dosh","Vastu Shanti","Kundali Milan","Graha Shanti"], specializations:["astrological","shanti"], languages:["Hindi","English"], rating:4.7, reviews:150, completed_pujas:1200, location:"Ujjain, MP", available:true, featured:true, image_url:"/assets/pandits/p3.jpg", bio:"Provides astrological guidance and performs precise dosh shanti pujas based on birth charts.", certifications:["Jyotish Acharya (Vikram University)","Vastu Consultant"] },
  { id:"p4", name:"Acharya Suresh Dwivedi", slug:"acharya-suresh-dwivedi", title:"Katha Vachak & Havan Specialist", experience:18, experience_label:"18+ Years", expertise:["Bhagwat Katha","Sundarkand","Rudrabhishek","Ram Katha","Shiv Mahapuran"], specializations:["mahayagya","regular","festival"], languages:["Hindi","Sanskrit","Marathi"], rating:4.8, reviews:210, completed_pujas:1900, location:"Nashik, MH", available:true, featured:false, image_url:"/assets/pandits/p4.jpg", bio:"An engaging Katha Vachak who brings scriptures to life with storytelling.", certifications:["Acharya (Rashtriya Sanskrit Sansthan)","Vedic Ritual Expert"] },
  { id:"p5", name:"Pandit Manoj Mishra", slug:"pandit-manoj-mishra", title:"Vivah & Samskara Specialist", experience:12, experience_label:"12+ Years", expertise:["Vivah","Namkaran","Mundan","Upanayana","Lakshmi Puja","Annaprashan"], specializations:["samskara","prosperity"], languages:["Hindi","Sanskrit","English","Gujarati"], rating:4.8, reviews:160, completed_pujas:1100, location:"Ahmedabad, GJ", available:true, featured:false, image_url:"/assets/pandits/p5.jpg", bio:"Specializes in wedding ceremonies and life-event samskaras.", certifications:["Shastri (Gujarat Vidyapith)","Samskara Karmakand Diploma"] },
  { id:"p6", name:"Acharya Dinesh Joshi", slug:"acharya-dinesh-joshi", title:"Tantrik & Dosh Nivaran Expert", experience:22, experience_label:"22+ Years", expertise:["Kaal Sarp Dosh","Navagraha Shanti","Pitra Dosh","Mangal Dosh","Baglamukhi","Kali Puja"], specializations:["astrological","tantra","pitru"], languages:["Hindi","Sanskrit"], rating:4.7, reviews:130, completed_pujas:950, location:"Haridwar, UK", available:true, featured:false, image_url:"/assets/pandits/p6.jpg", bio:"A deeply knowledgeable Tantrik Acharya specializing in dosh nivaran and Shakti pujas.", certifications:["Tantra Shastra Acharya","Jyotish Ratna"] },
  { id:"p7", name:"Pandit Hari Om Shukla", slug:"pandit-hari-om-shukla", title:"Pitru Karma & Shraddh Specialist", experience:28, experience_label:"28+ Years", expertise:["Pind Daan","Shraddh","Narayan Bali","Pitru Tarpan","Asthi Visarjan","Garud Puran"], specializations:["pitru","mahayagya"], languages:["Hindi","Sanskrit"], rating:4.9, reviews:175, completed_pujas:2200, location:"Gaya, Bihar", available:true, featured:true, image_url:"/assets/pandits/p7.jpg", bio:"One of the most experienced Pind Daan and Shraddh karma specialists in Gaya.", certifications:["Shastri (Magadh University)","Pitru Karma Visharad"] },
  { id:"p8", name:"Acharya Krishnanand Tripathi", slug:"acharya-krishnanand-tripathi", title:"Navratri & Shakti Upasak", experience:20, experience_label:"20+ Years", expertise:["Navratri Puja","Durga Saptashati","Durga Puja","Kali Puja","Chamunda Puja","Devi Bhagwat"], specializations:["festival","tantra","mahayagya"], languages:["Hindi","Sanskrit","Bengali"], rating:4.8, reviews:195, completed_pujas:1600, location:"Kolkata, WB", available:true, featured:false, image_url:"/assets/pandits/p8.jpg", bio:"A devoted Shakti Upasak and Navratri specialist.", certifications:["Tantra Vidya (Kamakhya)","Acharya in Shakti Upasana"] },
  { id:"p9", name:"Pandit Govind Prasad Upadhyay", slug:"pandit-govind-prasad", title:"Ganesh & Festival Puja Expert", experience:14, experience_label:"14+ Years", expertise:["Ganesh Puja","Ganesh Chaturthi","Saraswati Puja","Basant Panchami","Tulsi Vivah","Surya Puja"], specializations:["regular","festival"], languages:["Hindi","Sanskrit","Marathi","English"], rating:4.7, reviews:140, completed_pujas:980, location:"Pune, MH", available:true, featured:false, image_url:"/assets/pandits/p9.jpg", bio:"A Ganesh bhakt and festival puja specialist.", certifications:["Shastri (Tilak Maharashtra Vidyapeeth)","Karmakand Certificate"] },
  { id:"p10", name:"Acharya Raghunath Dixit", slug:"acharya-raghunath-dixit", title:"Shanti Karma & Nakshatra Expert", experience:24, experience_label:"24+ Years", expertise:["Nakshatra Shanti","Bhoomi Puja","Shanti Path","Graha Shanti","Sarva Karya Siddhi"], specializations:["shanti","astrological"], languages:["Hindi","Sanskrit","English"], rating:4.8, reviews:165, completed_pujas:1400, location:"Indore, MP", available:true, featured:false, image_url:"/assets/pandits/p10.jpg", bio:"A specialist in Shanti Karma and nakshatra-based rituals.", certifications:["Jyotish Visharad","Shanti Karma Diploma (Ujjain)"] },
  { id:"p11", name:"Pandit Arvind Chaturvedi", slug:"pandit-arvind-chaturvedi", title:"Health & Mrityunjaya Specialist", experience:16, experience_label:"16+ Years", expertise:["Maha Mrityunjaya Havan","Ayush Homam","Dhanvantari Puja","Sudarshan Havan","Santan Gopal"], specializations:["health","regular"], languages:["Hindi","Sanskrit"], rating:4.8, reviews:135, completed_pujas:1050, location:"Rishikesh, UK", available:true, featured:false, image_url:"/assets/pandits/p11.jpg", bio:"Dedicated to healing pujas and health rituals.", certifications:["Acharya (Dev Sanskriti University)","Ayurveda Basics Diploma"] },
  { id:"p12", name:"Pandit Deepak Pathak", slug:"pandit-deepak-pathak", title:"Prosperity & Business Puja Expert", experience:13, experience_label:"13+ Years", expertise:["Lakshmi Puja","Kuber Puja","Vyapar Vriddhi","Dhanteras","Diwali Puja","Sri Sukta Havan"], specializations:["prosperity","festival"], languages:["Hindi","English","Gujarati"], rating:4.7, reviews:120, completed_pujas:870, location:"Surat, GJ", available:true, featured:false, image_url:"/assets/pandits/p12.jpg", bio:"Popular among business families for his prosperity rituals.", certifications:["Shastri (Somnath Sanskrit University)","Vaishya Karmakand Specialist"] },
];

// ── Pujas ──
const pujas = [
  { id:"bhagwat-katha", title:"Srimad Bhagwat Katha", slug:"bhagwat-katha", category_id:"mahayagya", short_description:"A 7-day grand spiritual journey for liberation and ancestral peace.", description:"Srimad Bhagwat Katha is a deeply spiritual recitation of the divine leelas of Lord Krishna. Spanning 7 days, it purifies the listener, removes karmic debts, and grants liberation (Moksha).", image_url:"/assets/pujas/bhagwat.jpg", gallery_images:["/assets/pujas/bhagwat-1.jpg","/assets/pujas/bhagwat-2.jpg","/assets/pujas/bhagwat-3.jpg"], rating:4.9, reviews:120, bookings:340, duration:"7 Days", pandit_ids:["p1","p4"], tags:["popular","grand","family"], benefits:["Ancestral peace (Pitru Tarpan)","Karmic debt removal","Family harmony","Spiritual elevation"], tiers:{"basic":{"name":"Basic","price":51000,"originalPrice":61000,"pandits":1,"features":["1 Main Pandit (Vyas)","Basic Samagri Kit","Daily 4-hour Katha session","Simple Vedi setup"]},"standard":{"name":"Standard","price":151000,"originalPrice":175000,"pandits":3,"features":["3 Pandits including Katha Vyas","Premium Samagri Kit","Daily 6-hour Katha with Bhajan","Decorated Vedi & Stage","Live harmonium-tabla group","Photo documentation"]},"premium":{"name":"Premium (VVIP)","price":501000,"originalPrice":551000,"pandits":11,"features":["11 Pandits with renowned Katha Vyas","Exclusive VVIP Samagri Collection","Daily 8-hour Katha with full cultural program","Grand Stage with floral decor","Professional sound & projector setup","Live-streaming option","Dedicated event coordinator","Photo + Video documentation"]}}, samagri_list:[{"name":"Bhagwat Granth (Gita Press)","qty":"1 Set","essential":true},{"name":"Singhasan for Granth","qty":"1 Piece","essential":true},{"name":"Pure Cow Ghee","qty":"5 Kg","essential":true},{"name":"Panchamrit","qty":"1 Set","essential":true},{"name":"Mango Leaves","qty":"100 Leaves","essential":true},{"name":"Kalash with Coconut","qty":"1 Set","essential":true},{"name":"Marigold & Rose Garlands","qty":"10 Garlands","essential":false},{"name":"Dhoop, Agarbatti & Camphor","qty":"1 Pack Each","essential":true},{"name":"Havan Samagri","qty":"2 Kg","essential":true},{"name":"Chandan Paste & Kumkum","qty":"200 gm Each","essential":true}] },
  { id:"vivah-puja", title:"Vedic Vivah (Wedding) Puja", slug:"vedic-vivah", category_id:"samskara", short_description:"Traditional Vedic wedding ceremony with every mantra and ritual performed by expert Pandits.", description:"Our Pandits ensure that every mantra and ritual of the wedding is performed with absolute purity and correct pronunciation.", image_url:"/assets/pujas/wedding.jpg", gallery_images:["/assets/pujas/wedding-1.jpg","/assets/pujas/wedding-2.jpg","/assets/pujas/wedding-3.jpg"], rating:4.8, reviews:200, bookings:580, duration:"4-6 Hours", pandit_ids:["p1","p2","p5"], tags:["popular","samskara","family"], benefits:["Shastriya Vedic wedding","Proper Kanyadaan & Saptapadi","Mangal Phera with correct rituals","Blessings for a lifelong bond"], tiers:{"basic":{"name":"Basic","price":11000,"originalPrice":15000,"pandits":2,"features":["2 Pandits","Standard Samagri Kit","Core wedding rituals","Simple Havan Kund setup"]},"standard":{"name":"Standard","price":31000,"originalPrice":39000,"pandits":5,"features":["5 Pandits with lead Acharya","Premium Samagri Kit","Full Vedic ritual sequence","Decorated Vedi with flowers","Shehnai music arrangement"]},"premium":{"name":"Premium (Royal)","price":101000,"originalPrice":121000,"pandits":11,"features":["11 Pandits with senior Acharya","Elite Samagri Collection","Grand Vedi with floral & light decor","Musical Phere with live Shehnai","Vedic choir chanting","Custom ritual booklet","Photo + Video documentation","Dedicated event manager"]}}, samagri_list:[{"name":"Maalayein (Jaimala Garlands)","qty":"2 Sets","essential":true},{"name":"Mangal Sutra","qty":"1 Piece","essential":true},{"name":"Havan Kund (Copper)","qty":"1 Piece","essential":true},{"name":"Havan Samagri","qty":"2 Kg","essential":true},{"name":"Pure Cow Ghee","qty":"2 Kg","essential":true}] },
  { id:"satyanarayan-katha", title:"Satyanarayan Vrat Katha", slug:"satyanarayan-katha", category_id:"regular", short_description:"Auspicious puja for wealth, health and prosperity — ideal before new beginnings.", description:"Lord Satyanarayan is the embodiment of truth. This puja is performed before auspicious events, on Purnima, or to mark life milestones.", image_url:"/assets/pujas/satyanarayan.jpg", gallery_images:["/assets/pujas/satyanarayan-1.jpg","/assets/pujas/satyanarayan-2.jpg"], rating:4.9, reviews:450, bookings:1240, duration:"2-3 Hours", pandit_ids:["p2","p3"], tags:["popular","bestseller","household"], benefits:["Financial prosperity","Family harmony","Obstacle removal","Auspicious beginning for new ventures"], tiers:{"basic":{"name":"Basic","price":2100,"originalPrice":2800,"pandits":1,"features":["1 Pandit","Basic Samagri Kit","Complete Katha recitation","Standard Prasad"]},"standard":{"name":"Standard","price":5100,"originalPrice":6500,"pandits":2,"features":["2 Pandits","Premium Samagri Kit","Extended Katha with explanation","Aarti & Bhajan session","Sheera Prasad for 25 people"]},"premium":{"name":"Premium (Grand)","price":11000,"originalPrice":14000,"pandits":3,"features":["3 Pandits","Special Samagri","Full Katha with live Kirtan","Havan after Katha","Sheera Prasad for 50 people","Flower decoration"]}}, samagri_list:[{"name":"Satyanarayan Katha Book","qty":"1 Piece","essential":true},{"name":"Panchamrit Ingredients","qty":"1 Set","essential":true},{"name":"Banana Leaves","qty":"5 Leaves","essential":true},{"name":"Seasonal Fruits","qty":"5 Types","essential":true}] },
  { id:"griha-pravesh", title:"Griha Pravesh (Housewarming) Puja", slug:"griha-pravesh", category_id:"regular", short_description:"Sacred housewarming ritual to purify your new home and invite prosperity.", description:"Griha Pravesh Puja sanctifies your new home, removes negative energies through Vastu Havan, and invites Goddess Lakshmi and Lord Ganesha.", image_url:"/assets/pujas/griha-pravesh.jpg", gallery_images:["/assets/pujas/griha-pravesh-1.jpg","/assets/pujas/griha-pravesh-2.jpg"], rating:4.8, reviews:310, bookings:870, duration:"3-4 Hours", pandit_ids:["p2","p3"], tags:["popular","household","vastu"], benefits:["Vastu dosh removal","Negative energy cleansing","Prosperity invitation","Protection for family"], tiers:{"basic":{"name":"Basic","price":3100,"originalPrice":4000,"pandits":1,"features":["1 Pandit","Basic Samagri Kit","Ganesh Puja + Griha Pravesh Vidhi","Standard Havan"]},"standard":{"name":"Standard","price":7100,"originalPrice":9000,"pandits":2,"features":["2 Pandits","Premium Samagri Kit","Ganesh Puja + Vastu Shanti + Griha Pravesh","Navagraha Havan","Room-by-room purification"]},"premium":{"name":"Premium (Complete)","price":15100,"originalPrice":19000,"pandits":3,"features":["3 Pandits","Complete Samagri with Vastu items","Full Vastu Shanti + Navagraha + Griha Pravesh","Complete home purification","Lakshmi-Ganesh Sthapana","Havan with 108 Aahutis","Prasad for 30 people"]}}, samagri_list:[{"name":"Kalash (Copper) with Coconut","qty":"1 Set","essential":true},{"name":"Gangajal","qty":"500 ml","essential":true},{"name":"Havan Samagri","qty":"1.5 Kg","essential":true}] },
  { id:"navagraha-shanti", title:"Navagraha Shanti Puja", slug:"navagraha-shanti", category_id:"astrological", short_description:"Appease all 9 planets to remove obstacles, bad luck, and dasha-related issues.", description:"When planetary positions are unfavorable, they can cause health, financial and relationship issues. Navagraha Shanti Puja restores balance.", image_url:"/assets/pujas/navagraha.jpg", gallery_images:["/assets/pujas/navagraha-1.jpg","/assets/pujas/navagraha-2.jpg"], rating:4.7, reviews:185, bookings:520, duration:"3-4 Hours", pandit_ids:["p3","p6"], tags:["astrological","dosh-nivaran"], benefits:["Planetary balance restoration","Bad dasha relief","Health improvement","Career & financial obstacle removal"], tiers:{"basic":{"name":"Basic","price":3100,"originalPrice":4100,"pandits":1,"features":["1 Pandit (Jyotish)","Basic Navagraha Samagri","Mantra chanting for all 9 planets","Simple Havan"]},"standard":{"name":"Standard","price":7100,"originalPrice":9100,"pandits":2,"features":["2 Pandits","Premium Navagraha Samagri","Individual planet-specific mantras","Navagraha Havan with 9 Samidhas","Personalized kundali remedies"]},"premium":{"name":"Premium (Maha Shanti)","price":15100,"originalPrice":19100,"pandits":3,"features":["3 Pandits with senior Jyotish Acharya","Complete Samagri with gemstones","1008 mantra jaap per planet","Grand Navagraha Havan","Gemstone energization","Written remedial report","Follow-up consultation"]}}, samagri_list:[{"name":"Navagraha Yantra","qty":"1 Set","essential":true},{"name":"9 types of Grains","qty":"1 Kg Set","essential":true},{"name":"Havan Samagri","qty":"1.5 Kg","essential":true}] },
  { id:"sundarkand-path", title:"Sundarkand Path", slug:"sundarkand-path", category_id:"mahayagya", short_description:"Powerful recitation of Sundarkand from Ramcharitmanas for obstacle removal and courage.", description:"Sundarkand is the most powerful chapter of Tulsidas's Ramcharitmanas, describing Hanuman Ji's journey to Lanka.", image_url:"/assets/pujas/sundarkand.jpg", gallery_images:["/assets/pujas/sundarkand-1.jpg","/assets/pujas/sundarkand-2.jpg"], rating:4.9, reviews:280, bookings:760, duration:"3-5 Hours", pandit_ids:["p1","p4"], tags:["popular","hanuman","protection"], benefits:["Obstacle & fear removal","Health recovery support","Court case & legal relief","Protection from negative energies"], tiers:{"basic":{"name":"Basic","price":2100,"originalPrice":3000,"pandits":1,"features":["1 Pandit","Basic Samagri Kit","Complete Sundarkand recitation","Hanuman Aarti"]},"standard":{"name":"Standard","price":5100,"originalPrice":7000,"pandits":2,"features":["2 Pandits","Premium Samagri Kit","Sundarkand with Doha explanation","Hanuman Chalisa Jaap (11 times)","Havan after Path","Prasad for 25 people"]},"premium":{"name":"Premium (Akhand)","price":11000,"originalPrice":15000,"pandits":5,"features":["5 Pandits","Complete Samagri with Singhasan","Akhand Sundarkand (continuous recitation)","Hanuman Chalisa 108 times","Grand Havan with 1008 Aahutis","Live Bhajan Mandali","Prasad for 50 people"]}}, samagri_list:[{"name":"Ramcharitmanas (Sundarkand)","qty":"1 Book","essential":true},{"name":"Red Cloth","qty":"2 Meters","essential":true},{"name":"Pure Cow Ghee","qty":"1 Kg","essential":true}] },
  { id:"namkaran-sanskar", title:"Namkaran Sanskar (Naming Ceremony)", slug:"namkaran-sanskar", category_id:"samskara", short_description:"Sacred Vedic naming ceremony for your newborn with proper astrological guidance.", description:"Namkaran is one of the 16 Vedic Samskaras. The baby's name is chosen based on their birth nakshatra and planetary positions.", image_url:"/assets/pujas/namkaran.jpg", gallery_images:["/assets/pujas/namkaran-1.jpg","/assets/pujas/namkaran-2.jpg"], rating:4.8, reviews:165, bookings:430, duration:"1.5-2 Hours", pandit_ids:["p2","p3"], tags:["samskara","baby","family"], benefits:["Astrologically aligned name selection","Blessings for newborn's health","Family bonding ceremony","Vedic Samskara fulfillment"], tiers:{"basic":{"name":"Basic","price":2100,"originalPrice":3000,"pandits":1,"features":["1 Pandit","Basic Samagri Kit","Ganesh Puja + Namkaran Vidhi","3 name suggestions"]},"standard":{"name":"Standard","price":5100,"originalPrice":6500,"pandits":2,"features":["2 Pandits","Premium Samagri Kit","Ganesh Puja + Havan + Namkaran","Detailed kundali with 5 names","Gold pen for name writing","Prasad for 20 people"]},"premium":{"name":"Premium (Grand)","price":11000,"originalPrice":14000,"pandits":3,"features":["3 Pandits with Jyotish Acharya","Premium Samagri with silver items","Complete ceremony with Havan","Full birth chart + 10 name options","Silver coin gift for baby","Puja area decoration","Prasad for 50 people"]}}, samagri_list:[{"name":"Golden/Silver Plate","qty":"1 Piece","essential":true},{"name":"Honey","qty":"50 ml","essential":true},{"name":"Pure Cow Ghee","qty":"500 gm","essential":true}] },
  { id:"kaal-sarp-dosh", title:"Kaal Sarp Dosh Nivaran Puja", slug:"kaal-sarp-dosh", category_id:"astrological", short_description:"Remove the effects of Kaal Sarp Dosh from your kundali for a peaceful life.", description:"When all planets are hemmed between Rahu and Ketu, it forms Kaal Sarp Dosh — causing delays, failures, and anxiety.", image_url:"/assets/pujas/kaalsarp.jpg", gallery_images:["/assets/pujas/kaalsarp-1.jpg","/assets/pujas/kaalsarp-2.jpg"], rating:4.7, reviews:140, bookings:390, duration:"3-4 Hours", pandit_ids:["p3","p6"], tags:["astrological","dosh-nivaran","rahu-ketu"], benefits:["Kaal Sarp Dosh neutralization","Mental peace & anxiety relief","Career & marriage obstacle removal","Protection from sudden losses"], tiers:{"basic":{"name":"Basic","price":5100,"originalPrice":6500,"pandits":1,"features":["1 Pandit (Jyotish)","Standard Samagri Kit","Nag Puja + Rahu-Ketu Shanti","Mantra Jaap (1008 times)"]},"standard":{"name":"Standard","price":11000,"originalPrice":14000,"pandits":2,"features":["2 Pandits","Premium Samagri Kit","Complete Kaal Sarp Nivaran Vidhi","Maha Mrityunjaya Jaap (11,000 times)","Personalized remedies"]},"premium":{"name":"Premium (Maha Nivaran)","price":21000,"originalPrice":27000,"pandits":3,"features":["3 Pandits with Tantrik Acharya","Complete Nivaran Samagri with Silver Nag","Extended 12-type analysis","Grand Havan","Silver Nag Pratima Daan","Rudrabhishek add-on","Written remedial plan","Follow-up call"]}}, samagri_list:[{"name":"Silver/Metal Nag Pratima","qty":"1 Piece","essential":true},{"name":"Black Sesame","qty":"1 Kg","essential":true},{"name":"Havan Samagri","qty":"1.5 Kg","essential":true}] },
  { id:"rudrabhishek", title:"Rudrabhishek Puja", slug:"rudrabhishek", category_id:"regular", short_description:"Sacred abhishek of Lord Shiva with Vedic mantras for health, success, and inner peace.", description:"Rudrabhishek is the most powerful form of Shiva worship. The Shivling is bathed with milk, honey, curd while chanting Rudram and Chamakam.", image_url:"/assets/pujas/rudrabhishek.jpg", gallery_images:["/assets/pujas/rudrabhishek-1.jpg","/assets/pujas/rudrabhishek-2.jpg"], rating:4.9, reviews:220, bookings:610, duration:"2-3 Hours", pandit_ids:["p1","p4"], tags:["shiva","popular","health"], benefits:["Disease & health issue relief","Sin removal","Wish fulfillment","Inner peace & spiritual growth"], tiers:{"basic":{"name":"Basic","price":3100,"originalPrice":4100,"pandits":1,"features":["1 Pandit","Basic Abhishek Samagri","Rudram Chanting","Shivling Abhishek with Panchamrit"]},"standard":{"name":"Standard","price":7100,"originalPrice":9100,"pandits":2,"features":["2 Pandits","Premium Abhishek Samagri","Rudram-Chamakam full chanting","Abhishek with 11 items","Bilva Patra Archana (108)","Havan after Abhishek"]},"premium":{"name":"Premium (Maha Rudrabhishek)","price":15100,"originalPrice":19000,"pandits":5,"features":["5 Pandits","Grand Abhishek Samagri","11 rounds Rudram-Chamakam","Abhishek with 21 items","1008 Bilva Patra Archana","Maha Havan","Shiva Tandav & Bhajan","Prasad for 50 people"]}}, samagri_list:[{"name":"Shivling (Narmadeshwar)","qty":"1 Piece","essential":true},{"name":"Raw Milk","qty":"2 Liters","essential":true},{"name":"Pure Cow Ghee","qty":"500 gm","essential":true}] },
  { id:"lakshmi-puja", title:"Lakshmi Puja (Wealth & Prosperity)", slug:"lakshmi-puja", category_id:"prosperity", short_description:"Invoke Goddess Lakshmi's blessings for wealth, business growth, and financial stability.", description:"Lakshmi Puja is performed to invite the blessings of Goddess Lakshmi — the deity of wealth, fortune, and prosperity.", image_url:"/assets/pujas/lakshmi.jpg", gallery_images:["/assets/pujas/lakshmi-1.jpg","/assets/pujas/lakshmi-2.jpg"], rating:4.8, reviews:195, bookings:540, duration:"2-3 Hours", pandit_ids:["p2","p5"], tags:["prosperity","diwali","business"], benefits:["Wealth & income increase","Business growth","Debt relief","Financial stability"], tiers:{"basic":{"name":"Basic","price":2100,"originalPrice":3000,"pandits":1,"features":["1 Pandit","Basic Lakshmi Puja Samagri","Ganesh-Lakshmi Puja Vidhi","Sri Sukta Chanting"]},"standard":{"name":"Standard","price":5100,"originalPrice":7000,"pandits":2,"features":["2 Pandits","Premium Samagri Kit","Ganesh-Lakshmi Puja + Sri Sukta (108)","Kuber Puja add-on","Prosperity Havan","Prasad for 25 people"]},"premium":{"name":"Premium (Maha Lakshmi)","price":11000,"originalPrice":14000,"pandits":3,"features":["3 Pandits","Grand Samagri with Silver Coin","Ashta Lakshmi Puja (all 8 forms)","Sri Sukta & Kanakdhara Stotra","Grand Havan with 1008 Aahutis","Yantra Sthapana & Energization","Bhajan Sandhya","Prasad for 50 people"]}}, samagri_list:[{"name":"Lakshmi-Ganesh Murti/Photo","qty":"1 Set","essential":true},{"name":"Kamal (Lotus) Flowers","qty":"11 Pieces","essential":true},{"name":"Pure Cow Ghee","qty":"500 gm","essential":true}] },
];

// ── Testimonials ──
const testimonials = [
  { id:"t1", name:"Rahul Verma", location:"Mumbai, MH", puja_booked:"griha-pravesh", puja_title:"Griha Pravesh Puja", text:"The Pandits from ShubhKarma performed our housewarming puja with incredible precision. Every mantra was clear, and they even explained each ritual to our family. Truly professional.", rating:5, date:"2026-01-15", image_url:"/assets/testimonials/t1.jpg", verified:true },
  { id:"t2", name:"Sneha Sharma", location:"Delhi, DL", puja_booked:"satyanarayan-katha", puja_title:"Satyanarayan Katha", text:"Booked the Standard package for Satyanarayan Katha. The samagri was 100% pure, the Prasad preparation was amazing, and the Pandit Ji's bhajan session was the highlight.", rating:5, date:"2026-01-28", image_url:"/assets/testimonials/t2.jpg", verified:true },
  { id:"t3", name:"Amit Patel", location:"Ahmedabad, GJ", puja_booked:"bhagwat-katha", puja_title:"Srimad Bhagwat Katha", text:"Organized a 7-day Bhagwat Katha for my parents' 50th anniversary. Acharya Ji's storytelling was mesmerizing. The entire colony attended.", rating:5, date:"2026-02-05", image_url:"/assets/testimonials/t3.jpg", verified:true },
  { id:"t4", name:"Priya Singh", location:"Lucknow, UP", puja_booked:"vivah-puja", puja_title:"Vedic Vivah", text:"Our wedding ceremony was flawless. The 5-Pandit team handled everything — from Kanyadaan to Saptapadi — with such grace.", rating:5, date:"2026-02-14", image_url:"/assets/testimonials/t4.jpg", verified:true },
  { id:"t5", name:"Vikram Joshi", location:"Pune, MH", puja_booked:"navagraha-shanti", puja_title:"Navagraha Shanti Puja", text:"Was going through a tough Shani Dasha. Pandit Ramakant Ji performed the Navagraha Shanti with great dedication. Within weeks, I could feel the shift.", rating:5, date:"2026-02-20", image_url:"/assets/testimonials/t5.jpg", verified:true },
  { id:"t6", name:"Meena Agarwal", location:"Jaipur, RJ", puja_booked:"rudrabhishek", puja_title:"Rudrabhishek Puja", text:"The Rudrabhishek was absolutely divine. The chanting of Rudram-Chamakam by 2 Pandits simultaneously gave me goosebumps.", rating:5, date:"2026-02-28", image_url:"/assets/testimonials/t6.jpg", verified:true },
  { id:"t7", name:"Suresh Reddy", location:"Hyderabad, TG", puja_booked:"lakshmi-puja", puja_title:"Lakshmi Puja", text:"Booked Lakshmi Puja for my new business launch. The Pandit was punctual, the Sri Sukta chanting was powerful. Business is thriving!", rating:5, date:"2026-03-05", image_url:"/assets/testimonials/t7.jpg", verified:true },
  { id:"t8", name:"Kavita Dubey", location:"Bhopal, MP", puja_booked:"namkaran-sanskar", puja_title:"Namkaran Sanskar", text:"Such a beautiful ceremony for our baby. Pandit Ji suggested 5 names based on the nakshatra. The family was so happy.", rating:5, date:"2026-03-10", image_url:"/assets/testimonials/t8.jpg", verified:true },
];

// ── Blog Posts ──
const blogPosts = [
  { id:"b1", title:"The Science Behind Havan: Why Ancient Fire Rituals Still Matter", slug:"science-behind-havan", excerpt:"Modern research confirms what Vedic rishis knew — havan purifies air, reduces bacteria, and creates a meditative environment.", category_id:"regular", tags:["havan","science","wellness"], author_name:"Acharya Veda Prakash", author_id:"p1", date:"2026-03-10", read_time:"6 min", image_url:"/assets/blog/havan-science.jpg", featured:true },
  { id:"b2", title:"Navagraha Shanti: Understanding the 9 Planets and Their Effects", slug:"navagraha-shanti-guide", excerpt:"Each planet governs specific life aspects. Learn how unfavorable planetary positions affect you.", category_id:"astrological", tags:["navagraha","astrology","remedies"], author_name:"Pandit Ramakant Sharma", author_id:"p3", date:"2026-03-05", read_time:"8 min", image_url:"/assets/blog/navagraha-guide.jpg", featured:true },
  { id:"b3", title:"The 7 Vedic Wedding Rituals Every Couple Should Know", slug:"vedic-wedding-rituals-explained", excerpt:"From Kanyadaan to Saptapadi — a deep dive into each ritual, its meaning, and why it matters.", category_id:"samskara", tags:["wedding","rituals","saptapadi"], author_name:"Pandit Manoj Mishra", author_id:"p5", date:"2026-02-28", read_time:"7 min", image_url:"/assets/blog/vedic-wedding.jpg", featured:false },
  { id:"b4", title:"Griha Pravesh 2026: Auspicious Dates and Complete Guide", slug:"griha-pravesh-2026-dates", excerpt:"Planning to move into your new home? Here are the most auspicious muhurat dates for 2026.", category_id:"regular", tags:["griha-pravesh","muhurat","2026"], author_name:"Pandit Ramakant Sharma", author_id:"p3", date:"2026-02-20", read_time:"5 min", image_url:"/assets/blog/griha-pravesh-guide.jpg", featured:false },
  { id:"b5", title:"Kaal Sarp Dosh: Myths, Reality, and Authentic Remedies", slug:"kaal-sarp-dosh-remedies", excerpt:"One of the most feared doshas. Separating myths from reality and how to genuinely address it.", category_id:"astrological", tags:["kaal-sarp","dosh","remedies"], author_name:"Acharya Dinesh Joshi", author_id:"p6", date:"2026-02-12", read_time:"9 min", image_url:"/assets/blog/kaalsarp-guide.jpg", featured:true },
  { id:"b6", title:"Why Rudrabhishek Is the Most Powerful Shiva Puja", slug:"rudrabhishek-power", excerpt:"The Rudram-Chamakam is the highest form of Shiva worship. Understand the 11 abhishek materials.", category_id:"regular", tags:["rudrabhishek","shiva","abhishek"], author_name:"Acharya Suresh Dwivedi", author_id:"p4", date:"2026-02-01", read_time:"6 min", image_url:"/assets/blog/rudrabhishek.jpg", featured:false },
];

// ── FAQ ──
const faqData = [
  { id:"f1", question:"Do I need to arrange samagri separately?", answer:"No. Our Pandits bring 100% pure and premium samagri based on the package you select. Every item is quality-checked before the puja.", category:"booking", sort_order:1 },
  { id:"f2", question:"How does payment work?", answer:"Pay a small booking amount online to confirm your slot. The remaining amount is paid after the puja is completed to your satisfaction.", category:"payment", sort_order:2 },
  { id:"f3", question:"Can I choose my Pandit?", answer:"Yes. You can view Pandit profiles, their expertise, and ratings before booking. If your preferred Pandit is unavailable, we'll suggest equally qualified alternatives.", category:"booking", sort_order:3 },
  { id:"f4", question:"What if I need to reschedule?", answer:"You can reschedule up to 24 hours before the puja at no extra cost. For same-day changes, a small rescheduling fee may apply.", category:"booking", sort_order:4 },
  { id:"f5", question:"Which cities do you serve?", answer:"We currently serve 25+ cities across India including Mumbai, Delhi, Bangalore, Hyderabad, Ahmedabad, Pune, Jaipur, Lucknow, Varanasi, and more.", category:"general", sort_order:5 },
  { id:"f6", question:"How are your Pandits verified?", answer:"Every Pandit undergoes a 3-step verification: educational certificate check, practical knowledge test, and background verification. Only 1 in 10 are selected.", category:"trust", sort_order:6 },
  { id:"f7", question:"What's included in the samagri kit?", answer:"Each puja has a specific samagri list. You can view the complete list on any puja's detail page. Premium packages include higher-quality items.", category:"general", sort_order:7 },
  { id:"f8", question:"Can I book a puja for a location outside India?", answer:"Currently we serve within India only. We're working on a virtual puja service where you can participate via live stream. Coming soon.", category:"general", sort_order:8 },
  { id:"f9", question:"What is the cancellation policy?", answer:"Full refund if cancelled 48+ hours before the puja. 50% refund for 24-48 hours. No refund for cancellations within 24 hours.", category:"payment", sort_order:9 },
  { id:"f10", question:"Do you provide muhurat consultation?", answer:"Yes. Our Jyotish Pandits can suggest the best muhurat for your puja based on your birth chart and panchang. Complimentary with Standard and Premium packages.", category:"general", sort_order:10 },
];

// ── Samagri Categories ──
const samagriCats = [
  { id:"kits", name:"Complete Puja Kits", icon:"package", slug:"puja-kits" },
  { id:"essentials", name:"Puja Essentials", icon:"flame", slug:"essentials" },
  { id:"ghee-oils", name:"Ghee & Oils", icon:"droplet", slug:"ghee-oils" },
  { id:"flowers", name:"Flowers & Mala", icon:"flower", slug:"flowers-mala" },
  { id:"woods", name:"Havan Woods & Herbs", icon:"tree", slug:"woods-herbs" },
  { id:"diyas", name:"Diyas & Lamps", icon:"lamp", slug:"diyas-lamps" },
];

// ── Samagri Products ──
const samagriProds = [
  { id:"s1", name:"Premium Havan Kit (51 items)", slug:"premium-havan-kit", category_id:"kits", price:1500, original_price:2000, description:"Complete set of 51 items required for a standard household havan.", puja_tags:["satyanarayan-katha","griha-pravesh","lakshmi-puja"], weight:"2.5 Kg", image_url:"/assets/samagri/havan-kit.jpg", images:["/assets/samagri/havan-kit.jpg","/assets/samagri/havan-kit-2.jpg"], in_stock:true, rating:4.8, reviews:89, featured:true },
  { id:"s2", name:"Satyanarayan Puja Complete Kit", slug:"satyanarayan-kit", category_id:"kits", price:1100, original_price:1500, description:"Everything needed for Satyanarayan Katha.", puja_tags:["satyanarayan-katha"], weight:"2 Kg", image_url:"/assets/samagri/satyanarayan-kit.jpg", images:["/assets/samagri/satyanarayan-kit.jpg"], in_stock:true, rating:4.9, reviews:124, featured:true },
  { id:"s3", name:"Vedic Vivah Complete Set", slug:"vivah-kit", category_id:"kits", price:5100, original_price:6500, description:"Every item needed for a Vedic wedding.", puja_tags:["vivah-puja"], weight:"5 Kg", image_url:"/assets/samagri/vivah-kit.jpg", images:["/assets/samagri/vivah-kit.jpg"], in_stock:true, rating:4.8, reviews:67, featured:true },
  { id:"s4", name:"Rudrabhishek Samagri Kit", slug:"rudrabhishek-kit", category_id:"kits", price:1800, original_price:2300, description:"Complete abhishek kit with Bilva Patra, Panchamrit items.", puja_tags:["rudrabhishek"], weight:"3 Kg", image_url:"/assets/samagri/rudrabhishek-kit.jpg", images:["/assets/samagri/rudrabhishek-kit.jpg"], in_stock:true, rating:4.7, reviews:53, featured:false },
  { id:"s5", name:"Navagraha Shanti Complete Kit", slug:"navagraha-kit", category_id:"kits", price:2100, original_price:2800, description:"9 types of grains, woods, flowers, and planet-specific offerings.", puja_tags:["navagraha-shanti","kaal-sarp-dosh"], weight:"3 Kg", image_url:"/assets/samagri/navagraha-kit.jpg", images:["/assets/samagri/navagraha-kit.jpg"], in_stock:true, rating:4.7, reviews:41, featured:false },
  { id:"s6", name:"Griha Pravesh Complete Kit", slug:"griha-pravesh-kit", category_id:"kits", price:1800, original_price:2400, description:"Vastu-approved housewarming kit with Gangajal, Kalash, and more.", puja_tags:["griha-pravesh"], weight:"3.5 Kg", image_url:"/assets/samagri/griha-pravesh-kit.jpg", images:["/assets/samagri/griha-pravesh-kit.jpg"], in_stock:true, rating:4.8, reviews:72, featured:false },
  { id:"s7", name:"Chandan Powder (Pure Sandalwood)", slug:"chandan-powder", category_id:"essentials", price:350, original_price:450, description:"100% pure Mysore sandalwood powder.", puja_tags:["all"], weight:"100 gm", image_url:"/assets/samagri/chandan.jpg", images:["/assets/samagri/chandan.jpg"], in_stock:true, rating:4.9, reviews:156, featured:false },
  { id:"s8", name:"Kumkum & Haldi Set", slug:"kumkum-haldi", category_id:"essentials", price:199, original_price:280, description:"Premium quality kumkum and organic haldi.", puja_tags:["all"], weight:"200 gm", image_url:"/assets/samagri/kumkum-haldi.jpg", images:["/assets/samagri/kumkum-haldi.jpg"], in_stock:true, rating:4.8, reviews:203, featured:false },
  { id:"s9", name:"Camphor (Bhimseni Kapoor)", slug:"bhimseni-kapoor", category_id:"essentials", price:250, original_price:320, description:"Pure Bhimseni Kapoor — burns without residue.", puja_tags:["all"], weight:"100 gm", image_url:"/assets/samagri/kapoor.jpg", images:["/assets/samagri/kapoor.jpg"], in_stock:true, rating:4.9, reviews:178, featured:true },
  { id:"s10", name:"Pure Cow Ghee (Bilona Method)", slug:"pure-cow-ghee", category_id:"ghee-oils", price:850, original_price:1000, description:"100% pure desi cow ghee extracted through bilona method.", puja_tags:["all"], weight:"1 Ltr", image_url:"/assets/samagri/ghee.jpg", images:["/assets/samagri/ghee.jpg"], in_stock:true, rating:4.9, reviews:312, featured:true },
  { id:"s11", name:"Til Oil (Sesame Oil)", slug:"sesame-oil", category_id:"ghee-oils", price:320, original_price:400, description:"Cold-pressed sesame oil for Shani Shanti and lamp offerings.", puja_tags:["navagraha-shanti","kaal-sarp-dosh"], weight:"500 ml", image_url:"/assets/samagri/til-oil.jpg", images:["/assets/samagri/til-oil.jpg"], in_stock:true, rating:4.7, reviews:67, featured:false },
  { id:"s12", name:"Havan Samagri (Premium Mixed Herbs)", slug:"havan-samagri", category_id:"woods", price:450, original_price:600, description:"Hand-mixed havan samagri with 36 sacred herbs.", puja_tags:["all"], weight:"1 Kg", image_url:"/assets/samagri/havan-samagri.jpg", images:["/assets/samagri/havan-samagri.jpg"], in_stock:true, rating:4.8, reviews:245, featured:true },
  { id:"s13", name:"Navagraha Samidha (9 Sacred Woods)", slug:"navagraha-samidha", category_id:"woods", price:550, original_price:700, description:"Authentic wood sticks for the 9 planets.", puja_tags:["navagraha-shanti","griha-pravesh"], weight:"1.5 Kg", image_url:"/assets/samagri/samidha.jpg", images:["/assets/samagri/samidha.jpg"], in_stock:true, rating:4.7, reviews:58, featured:false },
  { id:"s14", name:"Mango Wood Sticks (Aam Samidha)", slug:"mango-samidha", category_id:"woods", price:199, original_price:280, description:"Dried mango wood sticks for general havan use.", puja_tags:["all"], weight:"1 Kg", image_url:"/assets/samagri/mango-samidha.jpg", images:["/assets/samagri/mango-samidha.jpg"], in_stock:true, rating:4.6, reviews:134, featured:false },
  { id:"s15", name:"Fresh Marigold Garlands (Pack of 5)", slug:"marigold-garlands", category_id:"flowers", price:350, original_price:450, description:"Fresh, hand-strung marigold garlands.", puja_tags:["all"], weight:"500 gm", image_url:"/assets/samagri/marigold.jpg", images:["/assets/samagri/marigold.jpg"], in_stock:true, rating:4.6, reviews:89, featured:false },
  { id:"s16", name:"Tulsi Mala (Pack of 5)", slug:"tulsi-mala", category_id:"flowers", price:280, original_price:350, description:"Sacred Tulsi bead malas for wearing during puja.", puja_tags:["bhagwat-katha","satyanarayan-katha","lakshmi-puja"], weight:"100 gm", image_url:"/assets/samagri/tulsi-mala.jpg", images:["/assets/samagri/tulsi-mala.jpg"], in_stock:true, rating:4.8, reviews:97, featured:false },
  { id:"s17", name:"Brass Puja Diya (Medium)", slug:"brass-diya", category_id:"diyas", price:450, original_price:600, description:"Handcrafted brass diya with traditional design.", puja_tags:["all"], weight:"250 gm", image_url:"/assets/samagri/brass-diya.jpg", images:["/assets/samagri/brass-diya.jpg"], in_stock:true, rating:4.8, reviews:143, featured:false },
  { id:"s18", name:"Akhand Jyoti Lamp (Brass)", slug:"akhand-jyoti", category_id:"diyas", price:1200, original_price:1500, description:"Traditional brass Akhand Jyoti lamp for continuous flame.", puja_tags:["bhagwat-katha","sundarkand-path"], weight:"800 gm", image_url:"/assets/samagri/akhand-jyoti.jpg", images:["/assets/samagri/akhand-jyoti.jpg"], in_stock:true, rating:4.9, reviews:56, featured:true },
];

// ── Stats ──
const statsData = [
  { id:"pujas", label:"Pujas Performed", value:10000, display_value:"10,000+", icon:"flame", suffix:"+" },
  { id:"families", label:"Happy Families", value:8500, display_value:"8,500+", icon:"heart", suffix:"+" },
  { id:"pandits", label:"Verified Pandits", value:500, display_value:"500+", icon:"users", suffix:"+" },
  { id:"cities", label:"Cities Covered", value:25, display_value:"25+", icon:"mapPin", suffix:"+" },
  { id:"rating", label:"Average Rating", value:4.8, display_value:"4.8★", icon:"star", suffix:"★" },
];

// ── Promises ──
const promisesData = [
  { id:"verified", title:"Verified Pandits", description:"Every Pandit is degree-verified, knowledge-tested, and background-checked. Only 1 in 10 make the cut.", icon:"shieldCheck", sort_order:1 },
  { id:"samagri", title:"100% Pure Samagri", description:"Authentic, unadulterated puja materials — Bilona ghee, Bhimseni camphor, organic haldi. No compromises.", icon:"leaf", sort_order:2 },
  { id:"pricing", title:"Transparent Pricing", description:"What you see is what you pay. No hidden charges, no last-minute additions.", icon:"receipt", sort_order:3 },
  { id:"punctual", title:"Muhurat-Perfect Timing", description:"Our Pandits arrive before the muhurat. We understand that auspicious timing cannot be compromised.", icon:"clock", sort_order:4 },
  { id:"satisfaction", title:"Satisfaction Guaranteed", description:"Pay the balance only after the puja is complete. Not satisfied? We'll arrange a re-performance or full refund.", icon:"thumbsUp", sort_order:5 },
  { id:"support", title:"Dedicated Support", description:"A personal coordinator handles your booking from confirmation to completion. Available on call and WhatsApp.", icon:"headset", sort_order:6 },
];

// ═══════════════════════════════════════════
// Run seed
// ═══════════════════════════════════════════
async function seed() {
  console.log('Seeding ShubhKarma database...\n');

  await upsert('categories', categories);
  await upsert('pandits', pandits);
  await upsert('pujas', pujas);
  await upsert('testimonials', testimonials);
  await upsert('blog_posts', blogPosts);
  await upsert('faq', faqData);
  await upsert('samagri_categories', samagriCats);
  await upsert('samagri_products', samagriProds);
  await upsert('stats', statsData);
  await upsert('promises', promisesData);

  console.log('\n✅ Seed complete!');
}

seed().catch(console.error);
